#!/usr/bin/env bash
set -euo pipefail

# These seven commands were launched concurrently from a Python subprocess wrapper.
# Common environment for every command:
export OPENAI_BASE_URL=http://p1-r12-n4.bluevela.rmf.ibm.com:8321/v1
export OPENAI_API_KEY=dummy
export MCODE_CONTEXT_WINDOW=32768
export MCODE_MAX_NEW_TOKENS=4096
export MCODE_REACT_TIMEOUT=2400

uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids python/bowling,python/connect,python/dot-dsl,python/food-chain,python/forth,python/grep,python/ledger,python/markdown,python/meetup,python/ocr-numbers,python/paasio,python/palindrome-products,python/pig-latin,python/poker,python/pov,python/protein-translation,python/pythagorean-triplet,python/rectangles,python/rest-api,python/robot-simulator,python/satellite,python/scale-generator,python/sgf-parsing,python/simple-cipher,python/simple-linked-list,python/spiral-matrix,python/sublist,python/tournament,python/tree-building,python/variable-length-quantity,python/word-count,python/word-search,python/wordy,python/zebra-puzzle --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/python-main.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids python/affine-cipher,python/beer-song,python/book-store,python/bottle-song,python/dominoes,python/go-counting,python/grade-school,python/hangman,python/list-ops,python/phone-number,python/proverb,python/react,python/robot-name,python/transpose,python/two-bucket,python/zipper --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/python-remainder.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids go/alphametics,go/beer-song,go/book-store,go/bottle-song,go/bowling,go/connect,go/counter,go/crypto-square,go/dnd-character,go/dominoes,go/error-handling,go/food-chain,go/forth,go/hexadecimal,go/kindergarten-garden,go/ledger,go/markdown,go/matrix,go/octal,go/paasio,go/palindrome-products,go/pig-latin,go/poker,go/pov,go/protein-translation,go/react,go/robot-simulator,go/say,go/scale-generator,go/simple-linked-list,go/sublist,go/transpose,go/tree-building,go/trinary,go/two-bucket,go/variable-length-quantity,go/word-search,go/wordy,go/zebra-puzzle --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/go.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids cpp/all-your-base,cpp/allergies,cpp/bank-account,cpp/binary-search-tree,cpp/circular-buffer,cpp/clock,cpp/complex-numbers,cpp/crypto-square,cpp/diamond,cpp/dnd-character,cpp/gigasecond,cpp/grade-school,cpp/kindergarten-garden,cpp/knapsack,cpp/linked-list,cpp/meetup,cpp/parallel-letter-frequency,cpp/perfect-numbers,cpp/phone-number,cpp/queen-attack,cpp/robot-name,cpp/space-age,cpp/spiral-matrix,cpp/sublist,cpp/yacht,cpp/zebra-puzzle --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/cpp.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids rust/accumulate,rust/acronym,rust/alphametics,rust/book-store,rust/bowling,rust/decimal,rust/dot-dsl,rust/doubly-linked-list,rust/fizzy,rust/forth,rust/gigasecond,rust/grade-school,rust/grep,rust/luhn-from,rust/macros,rust/nucleotide-codons,rust/ocr-numbers,rust/parallel-letter-frequency,rust/pig-latin,rust/poker,rust/react,rust/robot-name,rust/say,rust/scale-generator,rust/simple-cipher,rust/two-bucket,rust/variable-length-quantity,rust/word-count,rust/wordy,rust/xorcism --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids javascript/affine-cipher,javascript/alphametics,javascript/beer-song,javascript/binary,javascript/book-store,javascript/bottle-song,javascript/bowling,javascript/complex-numbers,javascript/connect,javascript/food-chain,javascript/forth,javascript/go-counting,javascript/grade-school,javascript/grep,javascript/house,javascript/killer-sudoku-helper,javascript/ledger,javascript/list-ops,javascript/meetup,javascript/ocr-numbers,javascript/palindrome-products,javascript/parallel-letter-frequency,javascript/phone-number,javascript/pig-latin,javascript/poker,javascript/promises,javascript/queen-attack,javascript/rational-numbers,javascript/react,javascript/rectangles,javascript/resistor-color-trio,javascript/rest-api,javascript/robot-name,javascript/say,javascript/scale-generator,javascript/simple-linked-list,javascript/space-age,javascript/state-of-tic-tac-toe,javascript/sum-of-multiples,javascript/tournament,javascript/transpose,javascript/triangle,javascript/twelve-days,javascript/two-bucket,javascript/variable-length-quantity,javascript/word-search,javascript/wordy,javascript/zebra-puzzle,javascript/zipper --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/javascript.db
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids java/affine-cipher,java/all-your-base,java/alphametics,java/bank-account,java/book-store,java/bottle-song,java/bowling,java/change,java/circular-buffer,java/connect,java/custom-set,java/dominoes,java/food-chain,java/forth,java/go-counting,java/hangman,java/house,java/kindergarten-garden,java/ledger,java/mazy-mice,java/ocr-numbers,java/palindrome-products,java/phone-number,java/pig-latin,java/poker,java/pov,java/protein-translation,java/pythagorean-triplet,java/queen-attack,java/rational-numbers,java/react,java/resistor-color-trio,java/rest-api,java/satellite,java/series,java/sgf-parsing,java/simple-linked-list,java/state-of-tic-tac-toe,java/transpose,java/tree-building,java/twelve-days,java/two-bucket,java/variable-length-quantity,java/word-search,java/wordy,java/zebra-puzzle,java/zipper --shards 2 --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/java.db

# Recovery after the local supervisor timed out while JavaScript was still running remotely, and after one Rust shard was killed with exit -7.
scp -o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=accept-new 'skula@login3.bluevela.rmf.ibm.com:/u/skula/mcode-launch/bench-runs/bench-1777147151-71847765-Qwen-Qwen3.6-35B-A3B/results.db' research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/javascript.db
scp -o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=accept-new 'skula@login3.bluevela.rmf.ibm.com:/u/skula/mcode-launch/bench-runs/bench-1777147151-7e132c64-Qwen-Qwen3.6-35B-A3B/results-shards/20260425-195918/*.db' research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust-partial/
uv run mcode bench aider-polyglot --on bluevela --model Qwen/Qwen3.6-35B-A3B --backend openai --temperature 0.3 --loop-budget 20 --task-ids rust/robot-name,rust/scale-generator,rust/two-bucket,rust/word-count,rust/xorcism --db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust-missing-5-seq.db
uv run mcode merge-shards --force --out research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/results.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/python-main.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/python-remainder.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/go.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/cpp.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/java.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/javascript.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust-partial/results-shard-0.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust-partial/results-shard-1.db research/2026-04-25-aider-polyglot-control-loop/full-parallel-shards2-lock/rust-missing-5-seq.db
